version: "3"

volumes: 
  django-app-static-data:
  postgres-db:

services:
  postgres:
    image: postgres:alpine
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data/

  redis:
    image: bitnami/redis:latest
    ports:
      - 63791:6379
    environment:
      - REDIS_MASTER_PASSWORD=masterpw123
      - REDIS_PASSWORD=redispw123

  django:
    build: .
    ports:
      - 8001:8001
    environment:
      - SECRET_KEY=${DJ_SECRET_KEY:-secret}
      - DEBUG=True
      - ALLOWED_HOSTS=${DJ_ALLOWED_HOSTS:-*}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redispw123
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=config.settings.settings_docker
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-secret}
      - SLACK_SUPPORT_CHANNEL='#support-slack-integration'

      - WAIT_HOSTS=postgres:5432,redis:6379
      - WAIT_HOSTS_TIMEOUT=100
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
    depends_on:
      - postgres
      - redis
    command:
      - sh
      - -c
      - |
        ./../wait
        python manage.py migrate
        daphne -b 0.0.0.0 -p 8001 config.asgi:application
    volumes:
      - ./dj_app:/app
