version: "3"

volumes: 
  django-app-static-data:
  postgres-db:
  django-log-volume:

services:
  postgres:
    image: postgres:alpine
    container_name: workshop-chat-server-postgres
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data/

  redis:
    image: bitnami/redis:latest
    container_name: workshop-chat-server-redis
    ports:
      - 63791:6379
    environment:
      - REDIS_MASTER_PASSWORD=masterpw123
      - REDIS_PASSWORD=redispw123

  django-chat-server:
    build: .
    container_name: workshop-chat-server-django-chat-server
    env_file: ./dj_app/.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redispw123
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=config.settings.settings_docker

      - WAIT_HOSTS=postgres:5432,redis:6379
      - WAIT_HOSTS_TIMEOUT=100
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
    depends_on:
      - postgres
      - redis
    command:
      - sh
      - -c
      - |
        ./../wait
        python manage.py migrate
        daphne -b 0.0.0.0 -p 8001 config.asgi:application
    volumes:
      - ./dj_app:/app
      - django-log-volume:/app/logs/

  nginx:
    image: nginx:1.21-alpine
    container_name: workshop-chat-server-nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/django-chat-server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django-chat-server

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: workshop-customer-platform-nginx-exporter
    ports:
      - 9113:9113
    command: -nginx.scrape-uri http://nginx/nginx/metrics
    depends_on:
      - nginx

  # TODO Remove Redis from dependencies
  django-kafka-consumer:
    build: .
    container_name: workshop-chat-server-django-kafka-consumer
    env_file: ./dj_app/.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redispw123
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=config.settings.settings_docker

      - WAIT_HOSTS=postgres:5432,redis:6379
      - WAIT_HOSTS_TIMEOUT=100
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
    depends_on:
      - postgres
      - redis
    command:
      - sh
      - -c
      - |
        ./../wait
        python manage.py migrate
        python manage.py consume_slack_messages
    volumes:
      - ./dj_app:/app
      - django-log-volume:/app/logs/

  filebeat:
    image: "docker.elastic.co/beats/filebeat:8.1.1"
    container_name: workshop-chat-server-filebeat
    env_file: ./dj_app/.env
    volumes:
      - ./elastic/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - django-log-volume:/logs
