# Generated by Django 3.2.7 on 2021-09-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackThread',
            fields=[
                ('source_thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.thread')),
                ('thread_ts', models.CharField(db_index=True, max_length=30)),
                ('source_type', models.CharField(max_length=20)),
                ('info', models.JSONField()),
                ('channel', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SlackResponseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('slack_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.slackthread')),
            ],
        ),
    ]
